################################################################################
# Copyright (c) 2018-2020, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################
# this  Makefile is to be used to build the test application to exercise the sample azure device client protocol adaptor
CXX:=g++
DS_INC:= ../../../includes

NVDS_VERSION:=6.0

DS_LIB:=/opt/nvidia/deepstream/deepstream-$(NVDS_VERSION)/lib/

SYNC_SEND_BIN:= test_azure_proto_sync
ASYNC_SEND_BIN:= test_azure_proto_async

SYNC_SEND_SRCS:=test_azure_proto_sync.c
ASYNC_SEND_SRCS:=test_azure_proto_async.c

CXXFLAGS:= -I$(DS_INC) -rdynamic
LDFLAGS:= -L$(DS_LIB) -ldl -lpthread -Wl,-rpath=$(DS_LIB)

default: all

all: $(SYNC_SEND_BIN) $(ASYNC_SEND_BIN)

$(SYNC_SEND_BIN) : $(SYNC_SEND_SRCS)
	$(CXX) -o $@ $^  $(CXXFLAGS) $(LDFLAGS)

$(ASYNC_SEND_BIN) : $(ASYNC_SEND_SRCS)
	$(CXX) -o $@ $^  $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf $(SYNC_SEND_BIN) $(ASYNC_SEND_BIN)

